apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: defsvrconnmqroute
  namespace: mq
spec:
  host: def2e-svrconn.chl.mq.ibm.com
  to:
    kind: Service
    name: qm2
  port:
    targetPort: 1414
  tls:
    termination: passthrough
