apiVersion: v1
kind: Service
metadata:
  labels:
    app: qm2
  name: qm2
  namespace: mq
spec:
  ports:
  - port: 1414
    protocol: TCP
    targetPort: 1414
  selector:
    app: qm2
  sessionAffinity: None
  type: ClusterIP
